safely extract version number

diff --git a/.github/checkout-build-openapi/action.yml b/.github/checkout-build-openapi/action.yml
--- a/.github/checkout-build-openapi/action.yml
+++ b/.github/checkout-build-openapi/action.yml
@@ -19,8 +19,18 @@ runs:
     - name: Get openapi version from pom
       id: get_openapi_version
       run: |
-        VERSION=$(mvn help:evaluate -Dexpression=test-test -q -DforceStdout)
-        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+#        Define allowed properties to get openapi version safely
+#        Protects against Log4Shell attack
+        case "${{ inputs.property-name }}" in
+          "payforlegalaid-openapi.version"
+            VERSION=$(mvn help:evaluate -Dexpression="${{ inputs.property-name }}" -q -DforceStdout)
+            echo "version=$VERSION" >> $GITHUB_OUTPUT
+            ;;
+          *)
+            echo "Error: Unauthorized property name"
+            exit 1
+            ;;
+        esac
       shell:
         bash
 
