updated db deployment script.

diff --git a/deployments/templates/deployment.yml b/deployments/templates/deployment.yml
--- a/deployments/templates/deployment.yml
+++ b/deployments/templates/deployment.yml
@@ -94,38 +94,28 @@ spec:
                       update
               }
               
-              cleanup() {
-                echo "Executing clean database strategy"              
+              validate() {
                 liquibase \
-                --url="$MOJFIN_DB_URL" \
-                --username="$MOJFIN_DEV_WRITE_USERNAME" \
-                --password="$MOJFIN_DEV_WRITE_PASSWORD" \
-                --changelog-file=${CHANGELOG_FILENAME} \
-                --searchPath=${BASE_FOLDER} \
-                drop-all --force
-              
-                echo "Database cleaned, reapplying migrations"
+                --changelog-file=${CHANGELOG_FILENAME}\ 
+                validate
               }
               
               echo "Checking database connectivity..."
               db_healthcheck
 
-              echo "Running initial Liquibase update..."
-              if run_update; then
-                  echo "✅ Liquibase update completed successfully"
-                  exit 0
-              fi
-
-              echo "⚠️ Initial update failed, performing clean and retrying..."
-              cleanup
-
-              echo "Running Liquibase update after clean..."
-              if run_update; then
-                  echo "✅ Liquibase update completed successfully after clean"
-                  exit 0
-              else
-                  echo "❌ Liquibase update failed even after clean"
-                  exit 1
+              echo "Validating changelog..."
+              if validate then
+                  echo "Running liquibase update..."
+                  if run_update; then
+                      echo "✅ Liquibase update completed successfully"
+                      exit 0
+                  else
+                      echo "❌ Liquibase update failed"
+                      exit 1
+                  fi
+              else 
+                 echo "❌ Error: Changelog Validation Failed"
+                 exit 1
               fi
 
           securityContext:
