check changelog size first

diff --git a/.github/workflows/deploy_api_to_env.yml b/.github/workflows/deploy_api_to_env.yml
--- a/.github/workflows/deploy_api_to_env.yml
+++ b/.github/workflows/deploy_api_to_env.yml
@@ -135,13 +135,20 @@ jobs:
           kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
           kubectl config use-context ${KUBE_CLUSTER}
           
+          CHANGELOG_FOLDER="payforlegalaid-data/data"
           ARCHIVE_NAME="liquibase-changelogs.tar.gz"
-
+          MAX_SIZE_MB=100
+          CURRENT_SIZE_MB=$(du -sm ${CHANGELOG_FOLDER} | cut -f1)          
+          
+          if [ "$CURRENT_SIZE_MB" -gt "$MAX_SIZE_MB" ]; then
+            echo "❌ Error: Changelogs are ${CURRENT_SIZE_MB}MB which exceeds the ${MAX_SIZE_MB}MB limit "
+            exit 1
+          fi
+          
           mkdir -p /tmp/liquibase-config
-          rsync -av --include="*.xml" payforlegalaid-data/data/* /tmp/liquibase-config/
+          rsync -av --include="*.xml" ${CHANGELOG_FOLDER}/* /tmp/liquibase-config/
 
           tar czf ${ARCHIVE_NAME} -C /tmp liquibase-config
-          cp payforlegalaid-data/data/master-changelog.xml changelog.tar.gz
           
           FOLDER_DIFF_SHA=$(sha256sum ${ARCHIVE_NAME} | cut -d' ' -f1)
   
